"""Metadata introspection for the SQLite Graph plugin used by cjm-ctl to generate the registration manifest.

Docs: https://cj-mills.github.io/cjm-graph-plugin-sqlitemeta.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/meta.ipynb.

# %% auto #0
__all__ = ['get_plugin_metadata']

# %% ../nbs/meta.ipynb #e175bfd5
import os
import sys
from typing import Any, Dict
from . import __version__

# %% ../nbs/meta.ipynb #dd05fac7
def get_plugin_metadata() -> Dict[str, Any]:  # Plugin metadata for manifest generation
    """Return metadata required to register this plugin with the PluginManager."""
    # Fallback base path (current behavior for backward compatibility)
    base_path = os.path.dirname(os.path.dirname(sys.executable))
    
    # Use CJM config if available, else fallback to env-relative paths
    cjm_data_dir = os.environ.get("CJM_DATA_DIR")
    
    # Plugin data directory
    plugin_name = "cjm-graph-plugin-sqlite"
    package_name = plugin_name.replace("-", "_")
    if cjm_data_dir:
        data_dir = os.path.join(cjm_data_dir, plugin_name)
    else:
        data_dir = os.path.join(base_path, "data")
    
    db_path = os.path.join(data_dir, "context_graph.db")
    
    # Ensure data directory exists
    os.makedirs(data_dir, exist_ok=True)

    return {
        "name": plugin_name,
        "version": __version__,
        "type": "graph",
        "category": "knowledge-management",
        # T30 / SG-7 fix: the interface lives in cjm-graph-plugin-system (the
        # interface library), NOT in this plugin's own package. Pre-fix the
        # f"{package_name}.plugin_interface.GraphPlugin" expression produced
        # the wrong FQN ("cjm_graph_plugin_sqlite.plugin_interface.GraphPlugin")
        # because package_name is derived from plugin_name. Substrate's runtime
        # fallback masked this; cjm-ctl validate per the audit's SG-7 design
        # catches it at install/release.
        "interface": "cjm_graph_plugin_system.plugin_interface.GraphPlugin",

        "module": f"{package_name}.plugin",
        "class": "SQLiteGraphPlugin",

        # Critical: The absolute path to THIS environment's python
        "python_path": sys.executable,

        "db_path": db_path,

        "resources": {
            "requires_gpu": False,
            "min_system_ram_mb": 512
        },

        "env_vars": {}
    }
