"""Plugin implementation for Context Graph using SQLite

Docs: https://cj-mills.github.io/cjm-graph-plugin-sqliteplugin.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/plugin.ipynb.

# %% auto #0
__all__ = ['SQLiteGraphPluginConfig', 'SQLiteGraphPlugin']

# %% ../nbs/plugin.ipynb #c187f00c
import json
import logging
import os
import sqlite3
from cjm_plugin_system.core.errors import PluginInputError
from cjm_plugin_system.core.interface import plugin_action, collect_plugin_actions
import time
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Tuple, Union

from cjm_plugin_system.utils.validation import (
    dict_to_config, config_to_dict, dataclass_to_jsonschema,
    SCHEMA_TITLE, SCHEMA_DESC
)
from cjm_graph_plugin_system.plugin_interface import GraphPlugin
from cjm_graph_plugin_system.core import (
    GraphNode, GraphEdge, GraphContext, GraphQuery, SourceRef
)

from .meta import get_plugin_metadata

# %% ../nbs/plugin.ipynb #6935e004
@dataclass
class SQLiteGraphPluginConfig:
    """Configuration for SQLite Graph Plugin."""
    db_path: Optional[str] = field(
        default=None,
        metadata={
            SCHEMA_TITLE: "Database Path",
            SCHEMA_DESC: "Absolute path to SQLite DB. If None, uses default env path."
        }
    )
    readonly: bool = field(
        default=False,
        metadata={
            SCHEMA_TITLE: "Read Only",
            SCHEMA_DESC: "Open database in read-only mode."
        }
    )

# %% ../nbs/plugin.ipynb #5b7e1ced
class SQLiteGraphPlugin(GraphPlugin):
    """Local, file-backed Context Graph implementation using SQLite."""

    config_class = SQLiteGraphPluginConfig

    def __init__(self):
        self.logger = logging.getLogger(f"{__name__}.{type(self).__name__}")
        self.config: SQLiteGraphPluginConfig = None
        self._db_path: str = None

    @property
    def name(self) -> str:  # Plugin name identifier
        """Get the plugin name identifier."""
        return "sqlite_graph"

    @property
    def version(self) -> str:  # Plugin version string
        """Get the plugin version string."""
        return "0.1.0"

    def get_current_config(self) -> Dict[str, Any]:  # Current configuration as dictionary
        """Return current configuration state."""
        if not self.config:
            return {}
        return config_to_dict(self.config)

    def get_config_schema(self) -> Dict[str, Any]:  # JSON Schema for configuration
        """Return JSON Schema for UI generation."""
        return dataclass_to_jsonschema(SQLiteGraphPluginConfig)

    def initialize(
        self,
        config: Optional[Any] = None  # Configuration dataclass, dict, or None
    ) -> None:
        """Initialize DB connection and schema."""
        self.config = dict_to_config(SQLiteGraphPluginConfig, config or {})

        # Determine DB path (Config override > Meta default)
        meta_path = get_plugin_metadata()["db_path"]
        self._db_path = self.config.db_path if self.config.db_path else meta_path

        self.logger.info(f"Initializing SQLite Graph at: {self._db_path}")
        # SG-41: a read-only graph must pre-exist; skip schema creation (the
        # read-only connection cannot run CREATE TABLE).
        if not self.config.readonly:
            self._init_db()

    def _init_db(self) -> None:
        """Create tables and indices."""
        with self._connect() as con:
            # Enable Foreign Keys
            con.execute("PRAGMA foreign_keys = ON;")

            # Nodes Table
            con.execute("""
                CREATE TABLE IF NOT EXISTS nodes (
                    id TEXT PRIMARY KEY,
                    label TEXT NOT NULL,
                    properties JSON,
                    sources JSON,
                    created_at REAL,
                    updated_at REAL
                )
            """)
            con.execute("CREATE INDEX IF NOT EXISTS idx_nodes_label ON nodes(label);")

            # Edges Table
            con.execute("""
                CREATE TABLE IF NOT EXISTS edges (
                    id TEXT PRIMARY KEY,
                    source_id TEXT NOT NULL,
                    target_id TEXT NOT NULL,
                    relation_type TEXT NOT NULL,
                    properties JSON,
                    created_at REAL,
                    updated_at REAL,
                    FOREIGN KEY(source_id) REFERENCES nodes(id) ON DELETE CASCADE,
                    FOREIGN KEY(target_id) REFERENCES nodes(id) ON DELETE CASCADE
                )
            """)
            con.execute("CREATE INDEX IF NOT EXISTS idx_edges_source ON edges(source_id);")
            con.execute("CREATE INDEX IF NOT EXISTS idx_edges_target ON edges(target_id);")
            con.execute("CREATE INDEX IF NOT EXISTS idx_edges_type ON edges(relation_type);")

    def _connect(self) -> sqlite3.Connection:  # Open DB connection (honors readonly; sets WAL + FKs)
        """Open a SQLite connection honoring the `readonly` config (SG-41).

        Read-only config opens the DB with URI `mode=ro` so any write raises at
        the SQLite layer. Read-write connections assert `journal_mode=WAL` (better
        concurrent-reader behavior; persists at the DB-file level) on each open.
        Foreign keys are enabled on every connection.
        """
        if self.config and self.config.readonly:
            con = sqlite3.connect(f"file:{self._db_path}?mode=ro", uri=True)
        else:
            con = sqlite3.connect(self._db_path)
            con.execute("PRAGMA journal_mode=WAL;")
        con.execute("PRAGMA foreign_keys = ON;")
        return con

    # -------------------------------------------------------------------------
    # Helpers
    # -------------------------------------------------------------------------

    def _row_to_node(
        self,
        row: Tuple  # DB row: (id, label, properties_json, sources_json, created_at, updated_at)
    ) -> GraphNode:  # Reconstructed GraphNode
        """Convert DB row to GraphNode DTO."""
        props = json.loads(row[2]) if row[2] else {}
        sources_raw = json.loads(row[3]) if row[3] else []
        sources = [SourceRef(**s) for s in sources_raw]
        return GraphNode(
            id=row[0], label=row[1], properties=props, sources=sources,
            created_at=row[4] if len(row) > 4 else None,
            updated_at=row[5] if len(row) > 5 else None,
        )

    def _row_to_edge(
        self,
        row: Tuple  # DB row: (id, source_id, target_id, relation_type, properties_json, created_at, updated_at)
    ) -> GraphEdge:  # Reconstructed GraphEdge
        """Convert DB row to GraphEdge DTO."""
        props = json.loads(row[4]) if row[4] else {}
        return GraphEdge(
            id=row[0], source_id=row[1], target_id=row[2],
            relation_type=row[3], properties=props,
            created_at=row[5] if len(row) > 5 else None,
            updated_at=row[6] if len(row) > 6 else None,
        )

    def _dict_to_node(
        self,
        data: Dict[str, Any]  # Node data as dictionary
    ) -> GraphNode:  # Reconstructed GraphNode
        """Convert dictionary to GraphNode, handling nested sources."""
        sources = []
        for s in data.get("sources", []):
            if isinstance(s, dict):
                sources.append(SourceRef(**s))
            else:
                sources.append(s)
        return GraphNode(
            id=data["id"],
            label=data["label"],
            properties=data.get("properties", {}),
            sources=sources,
            created_at=data.get("created_at"),
            updated_at=data.get("updated_at"),
        )

    def _dict_to_edge(
        self,
        data: Dict[str, Any]  # Edge data as dictionary
    ) -> GraphEdge:  # Reconstructed GraphEdge
        """Convert dictionary to GraphEdge."""
        return GraphEdge(
            id=data["id"],
            source_id=data["source_id"],
            target_id=data["target_id"],
            relation_type=data["relation_type"],
            properties=data.get("properties", {}),
            created_at=data.get("created_at"),
            updated_at=data.get("updated_at"),
        )

    # -------------------------------------------------------------------------
    # EXECUTE - @plugin_action dispatcher (SG-44)
    # -------------------------------------------------------------------------

    def execute(
        self,
        action: str = "get_schema",  # Action to perform
        **kwargs
    ) -> Dict[str, Any]:  # JSON-serializable result
        """Dispatch to the `@plugin_action`-tagged handler for `action` (SG-44).

        Handlers are discovered by walking the class MRO for methods carrying a
        `_plugin_action` tag (the same source `supported_actions` is built from
        via `collect_plugin_actions`). Replaces the prior hand-maintained
        if/elif chain.
        """
        for klass in type(self).__mro__:
            for attr in vars(klass).values():
                if getattr(attr, "_plugin_action", None) == action:
                    return attr(self, **kwargs)
        raise PluginInputError(  # SG-47: typed input-validation
            f"Unknown action: {action}", fields_invalid=["action"],
        )

    @plugin_action("get_schema")
    def _action_get_schema(self, **kwargs) -> Dict[str, Any]:
        """Action wrapper -> get_schema()."""
        return self.get_schema()

    @plugin_action("add_nodes")
    def _action_add_nodes(self, **kwargs) -> Dict[str, Any]:
        """Action wrapper -> add_nodes() (accepts dicts or GraphNode)."""
        nodes_data = kwargs.get("nodes", [])
        nodes = [self._dict_to_node(n) if isinstance(n, dict) else n for n in nodes_data]
        ids = self.add_nodes(nodes)
        return {"created_ids": ids, "count": len(ids)}

    @plugin_action("add_edges")
    def _action_add_edges(self, **kwargs) -> Dict[str, Any]:
        """Action wrapper -> add_edges() (accepts dicts or GraphEdge)."""
        edges_data = kwargs.get("edges", [])
        edges = [self._dict_to_edge(e) if isinstance(e, dict) else e for e in edges_data]
        ids = self.add_edges(edges)
        return {"created_ids": ids, "count": len(ids)}

    @plugin_action("get_node")
    def _action_get_node(self, **kwargs) -> Dict[str, Any]:
        """Action wrapper -> get_node()."""
        node = self.get_node(kwargs["node_id"])
        return {"node": node.to_dict() if node else None}

    @plugin_action("get_edge")
    def _action_get_edge(self, **kwargs) -> Dict[str, Any]:
        """Action wrapper -> get_edge()."""
        edge = self.get_edge(kwargs["edge_id"])
        return {"edge": edge.to_dict() if edge else None}

    @plugin_action("get_context")
    def _action_get_context(self, **kwargs) -> Dict[str, Any]:
        """Action wrapper -> get_context()."""
        ctx = self.get_context(
            kwargs["node_id"],
            depth=kwargs.get("depth", 1),
            filter_labels=kwargs.get("filter_labels"),
        )
        return ctx.to_dict()

    @plugin_action("find_nodes_by_source")
    def _action_find_nodes_by_source(self, **kwargs) -> Dict[str, Any]:
        """Action wrapper -> find_nodes_by_source()."""
        ref_data = kwargs["source_ref"]
        ref = SourceRef(**ref_data) if isinstance(ref_data, dict) else ref_data
        nodes = self.find_nodes_by_source(ref)
        return {"nodes": [n.to_dict() for n in nodes], "count": len(nodes)}

    @plugin_action("find_nodes_by_label")
    def _action_find_nodes_by_label(self, **kwargs) -> Dict[str, Any]:
        """Action wrapper -> find_nodes_by_label()."""
        nodes = self.find_nodes_by_label(kwargs["label"], limit=kwargs.get("limit", 100))
        return {"nodes": [n.to_dict() for n in nodes], "count": len(nodes)}

    @plugin_action("update_node")
    def _action_update_node(self, **kwargs) -> Dict[str, Any]:
        """Action wrapper -> update_node()."""
        return {"success": self.update_node(kwargs["node_id"], kwargs["properties"])}

    @plugin_action("update_edge")
    def _action_update_edge(self, **kwargs) -> Dict[str, Any]:
        """Action wrapper -> update_edge()."""
        return {"success": self.update_edge(kwargs["edge_id"], kwargs["properties"])}

    @plugin_action("delete_nodes")
    def _action_delete_nodes(self, **kwargs) -> Dict[str, Any]:
        """Action wrapper -> delete_nodes()."""
        count = self.delete_nodes(kwargs["node_ids"], cascade=kwargs.get("cascade", True))
        return {"deleted_count": count}

    @plugin_action("delete_edges")
    def _action_delete_edges(self, **kwargs) -> Dict[str, Any]:
        """Action wrapper -> delete_edges()."""
        return {"deleted_count": self.delete_edges(kwargs["edge_ids"])}

    @plugin_action("import_graph")
    def _action_import_graph(self, **kwargs) -> Dict[str, Any]:
        """Action wrapper -> import_graph() (dict or GraphContext)."""
        graph_data = kwargs["graph_data"]
        if isinstance(graph_data, dict):
            graph_data = GraphContext.from_dict(graph_data)
        return self.import_graph(graph_data, merge_strategy=kwargs.get("merge_strategy", "overwrite"))

    @plugin_action("export_graph")
    def _action_export_graph(self, **kwargs) -> Dict[str, Any]:
        """Action wrapper -> export_graph()."""
        return self.export_graph(filter_query=kwargs.get("filter_query")).to_dict()

    @plugin_action("query")
    def _action_query(self, **kwargs) -> Dict[str, Any]:
        """Action wrapper -> query() (read-only SELECT)."""
        return self.query(kwargs.get("sql", kwargs.get("query", "")), params=kwargs.get("params"))

    # -------------------------------------------------------------------------
    # CREATE
    # -------------------------------------------------------------------------

    def add_nodes(
        self,
        nodes: List[GraphNode]  # Nodes to create
    ) -> List[str]:  # Created node IDs
        """Bulk create nodes."""
        ids = []
        now = time.time()
        with self._connect() as con:
            for n in nodes:
                sources_json = json.dumps([s.to_dict() for s in n.sources])
                props_json = json.dumps(n.properties)
                try:
                    con.execute(
                        "INSERT INTO nodes (id, label, properties, sources, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?)",
                        (n.id, n.label, props_json, sources_json, now, now)
                    )
                    ids.append(n.id)
                except sqlite3.IntegrityError:
                    self.logger.warning(f"Node ID collision or error: {n.id}")
        return ids

    def add_edges(
        self,
        edges: List[GraphEdge]  # Edges to create
    ) -> List[str]:  # Created edge IDs
        """Bulk create edges."""
        ids = []
        now = time.time()
        with self._connect() as con:
            con.execute("PRAGMA foreign_keys = ON;")
            for e in edges:
                props_json = json.dumps(e.properties)
                try:
                    con.execute(
                        "INSERT INTO edges (id, source_id, target_id, relation_type, properties, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?)",
                        (e.id, e.source_id, e.target_id, e.relation_type, props_json, now, now)
                    )
                    ids.append(e.id)
                except sqlite3.IntegrityError as err:
                    self.logger.warning(f"Edge creation error (likely missing node): {err}")
        return ids

    # -------------------------------------------------------------------------
    # READ
    # -------------------------------------------------------------------------

    def get_node(
        self,
        node_id: str  # UUID of node to retrieve
    ) -> Optional[GraphNode]:  # Node or None if not found
        """Get a single node by ID."""
        with self._connect() as con:
            cur = con.execute(
                "SELECT id, label, properties, sources, created_at, updated_at FROM nodes WHERE id = ?",
                (node_id,)
            )
            row = cur.fetchone()
            return self._row_to_node(row) if row else None

    def get_edge(
        self,
        edge_id: str  # UUID of edge to retrieve
    ) -> Optional[GraphEdge]:  # Edge or None if not found
        """Get a single edge by ID."""
        with self._connect() as con:
            cur = con.execute(
                "SELECT id, source_id, target_id, relation_type, properties, created_at, updated_at FROM edges WHERE id = ?",
                (edge_id,)
            )
            row = cur.fetchone()
            return self._row_to_edge(row) if row else None

    def find_nodes_by_source(
        self,
        source_ref: SourceRef  # External resource reference
    ) -> List[GraphNode]:  # Nodes attached to this source
        """Find all nodes linked to a specific external resource."""
        # Use SQLite's json_each() to search within the sources JSON array
        query = """
            SELECT DISTINCT n.id, n.label, n.properties, n.sources, n.created_at, n.updated_at
            FROM nodes n, json_each(n.sources) as src
            WHERE json_extract(src.value, '$.plugin_name') = ?
              AND json_extract(src.value, '$.row_id') = ?
        """
        params = [source_ref.plugin_name, source_ref.row_id]

        # If segment slice is specified, add it to query
        if source_ref.segment_slice:
            query += " AND json_extract(src.value, '$.segment_slice') = ?"
            params.append(source_ref.segment_slice)

        results = []
        with self._connect() as con:
            cur = con.execute(query, tuple(params))
            for row in cur:
                results.append(self._row_to_node(row))
        return results

    def find_nodes_by_label(
        self,
        label: str,  # Node label to search for
        limit: int = 100  # Max results
    ) -> List[GraphNode]:  # Matching nodes
        """Find nodes by label."""
        results = []
        with self._connect() as con:
            cur = con.execute(
                "SELECT id, label, properties, sources, created_at, updated_at FROM nodes WHERE label = ? LIMIT ?",
                (label, limit)
            )
            for row in cur:
                results.append(self._row_to_node(row))
        return results

    def get_context(
        self,
        node_id: str,  # Starting node UUID
        depth: int = 1,  # Traversal depth (1 = immediate neighbors)
        filter_labels: Optional[List[str]] = None  # Only include nodes with these labels
    ) -> GraphContext:  # Subgraph containing node and its neighborhood
        """Get the neighborhood of a specific node."""
        # For depth=1, use simple query; for deeper, use recursive CTE
        edge_ids = []
        with self._connect() as con:
            if depth == 1:
                cur = con.execute(
                    "SELECT id FROM edges WHERE source_id = ? OR target_id = ?",
                    (node_id, node_id)
                )
            else:
                # Recursive CTE for multi-hop traversal
                query = """
                WITH RECURSIVE traversal(edge_id, node_id, depth) AS (
                    -- Base case: edges connected to the start node
                    SELECT id, 
                           CASE WHEN source_id = ? THEN target_id ELSE source_id END,
                           1
                    FROM edges
                    WHERE source_id = ? OR target_id = ?

                    UNION

                    -- Recursive step: edges connected to discovered nodes
                    SELECT e.id,
                           CASE WHEN e.source_id = t.node_id THEN e.target_id ELSE e.source_id END,
                           t.depth + 1
                    FROM edges e
                    JOIN traversal t ON (e.source_id = t.node_id OR e.target_id = t.node_id)
                    WHERE t.depth < ?
                )
                SELECT DISTINCT edge_id FROM traversal;
                """
                cur = con.execute(query, (node_id, node_id, node_id, depth))

            edge_ids = [row[0] for row in cur.fetchall()]

        # Fetch full Edge objects
        edges = []
        node_ids_in_context = {node_id}  # Always include the center

        if edge_ids:
            placeholders = ','.join('?' for _ in edge_ids)
            with self._connect() as con:
                cur = con.execute(
                    f"SELECT id, source_id, target_id, relation_type, properties, created_at, updated_at FROM edges WHERE id IN ({placeholders})",
                    tuple(edge_ids)
                )
                for row in cur:
                    e = self._row_to_edge(row)
                    edges.append(e)
                    node_ids_in_context.add(e.source_id)
                    node_ids_in_context.add(e.target_id)

        # Fetch full Node objects
        nodes = []
        if node_ids_in_context:
            placeholders = ','.join('?' for _ in node_ids_in_context)
            with self._connect() as con:
                sql = f"SELECT id, label, properties, sources, created_at, updated_at FROM nodes WHERE id IN ({placeholders})"

                # Apply optional label filtering
                params = list(node_ids_in_context)
                if filter_labels:
                    sql += f" AND label IN ({','.join('?' for _ in filter_labels)})"
                    params.extend(filter_labels)

                cur = con.execute(sql, tuple(params))
                for row in cur:
                    nodes.append(self._row_to_node(row))

        return GraphContext(
            nodes=nodes,
            edges=edges,
            metadata={"depth": depth, "center": node_id}
        )

    # -------------------------------------------------------------------------
    # UPDATE
    # -------------------------------------------------------------------------

    def update_node(
        self,
        node_id: str,  # UUID of node to update
        properties: Dict[str, Any]  # Properties to merge/update
    ) -> bool:  # True if successful
        """Partial update of node properties."""
        with self._connect() as con:
            # Fetch existing to merge
            cur = con.execute("SELECT properties FROM nodes WHERE id = ?", (node_id,))
            row = cur.fetchone()
            if not row:
                return False

            existing = json.loads(row[0]) if row[0] else {}
            existing.update(properties)  # Merge

            con.execute(
                "UPDATE nodes SET properties = ?, updated_at = ? WHERE id = ?",
                (json.dumps(existing), time.time(), node_id)
            )
            return True

    def update_edge(
        self,
        edge_id: str,  # UUID of edge to update
        properties: Dict[str, Any]  # Properties to merge/update
    ) -> bool:  # True if successful
        """Partial update of edge properties."""
        with self._connect() as con:
            cur = con.execute("SELECT properties FROM edges WHERE id = ?", (edge_id,))
            row = cur.fetchone()
            if not row:
                return False

            existing = json.loads(row[0]) if row[0] else {}
            existing.update(properties)

            con.execute(
                "UPDATE edges SET properties = ?, updated_at = ? WHERE id = ?",
                (json.dumps(existing), time.time(), edge_id)
            )
            return True

    # -------------------------------------------------------------------------
    # DELETE
    # -------------------------------------------------------------------------

    def delete_nodes(
        self,
        node_ids: List[str],  # UUIDs of nodes to delete
        cascade: bool = True  # Also delete connected edges
    ) -> int:  # Number of nodes deleted
        """Delete nodes (and optionally connected edges)."""
        with self._connect() as con:
            if cascade:
                con.execute("PRAGMA foreign_keys = ON;")  # Ensures cascade works
            else:
                con.execute("PRAGMA foreign_keys = OFF;")

            placeholders = ','.join('?' for _ in node_ids)
            cur = con.execute(
                f"DELETE FROM nodes WHERE id IN ({placeholders})",
                tuple(node_ids)
            )
            return cur.rowcount

    def delete_edges(
        self,
        edge_ids: List[str]  # UUIDs of edges to delete
    ) -> int:  # Number of edges deleted
        """Delete edges."""
        with self._connect() as con:
            placeholders = ','.join('?' for _ in edge_ids)
            cur = con.execute(
                f"DELETE FROM edges WHERE id IN ({placeholders})",
                tuple(edge_ids)
            )
            return cur.rowcount

    # -------------------------------------------------------------------------
    # LIFECYCLE & INTROSPECTION
    # -------------------------------------------------------------------------

    def get_schema(self) -> Dict[str, Any]:  # Graph schema/ontology
        """Return the current ontology/schema of the graph."""
        schema = {"node_labels": [], "edge_types": [], "counts": {}}
        with self._connect() as con:
            # Labels
            cur = con.execute("SELECT DISTINCT label FROM nodes")
            schema["node_labels"] = [r[0] for r in cur.fetchall()]

            # Types
            cur = con.execute("SELECT DISTINCT relation_type FROM edges")
            schema["edge_types"] = [r[0] for r in cur.fetchall()]

            # Counts
            cur = con.execute("SELECT label, COUNT(*) FROM nodes GROUP BY label")
            for row in cur:
                schema["counts"][row[0]] = row[1]

        return schema

    def import_graph(
        self,
        graph_data: GraphContext,  # Data to import
        merge_strategy: str = "overwrite"  # "overwrite", "skip", or "merge"
    ) -> Dict[str, int]:  # Import statistics {nodes_created, edges_created, merge_strategy}
        """Bulk import a GraphContext honoring merge_strategy (SG-41).

        On id-conflict: "skip" keeps the existing row untouched; "overwrite"
        replaces its mutable fields with the incoming values; "merge" unions
        properties (incoming wins per key) and unions node sources by identity.
        Brand-new ids are always inserted. The `nodes_created`/`edges_created`
        counts report rows written (inserted or updated).
        """
        if merge_strategy not in ("overwrite", "skip", "merge"):
            raise PluginInputError(  # SG-47: typed input-validation
                f"Unknown merge_strategy: {merge_strategy}", fields_invalid=["merge_strategy"],
            )
        n = self._import_nodes(graph_data.nodes, merge_strategy)
        e = self._import_edges(graph_data.edges, merge_strategy)
        return {"nodes_created": n, "edges_created": e, "merge_strategy": merge_strategy}

    def _import_nodes(
        self,
        nodes: List[GraphNode],  # Nodes to import
        merge_strategy: str  # "overwrite" | "skip" | "merge"
    ) -> int:  # Count of rows written (inserted or updated)
        """Import nodes honoring merge_strategy (see import_graph)."""
        now = time.time()
        written = 0
        with self._connect() as con:
            for node in nodes:
                props_json = json.dumps(node.properties)
                sources_json = json.dumps([s.to_dict() for s in node.sources])
                row = con.execute("SELECT properties, sources FROM nodes WHERE id = ?", (node.id,)).fetchone()
                if row is None:
                    con.execute(
                        "INSERT INTO nodes (id, label, properties, sources, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?)",
                        (node.id, node.label, props_json, sources_json, now, now),
                    )
                    written += 1
                elif merge_strategy == "skip":
                    continue
                elif merge_strategy == "overwrite":
                    con.execute(
                        "UPDATE nodes SET label = ?, properties = ?, sources = ?, updated_at = ? WHERE id = ?",
                        (node.label, props_json, sources_json, now, node.id),
                    )
                    written += 1
                else:  # merge
                    merged_props = json.loads(row[0]) if row[0] else {}
                    merged_props.update(node.properties)
                    existing_sources = json.loads(row[1]) if row[1] else []
                    seen = {(s.get("plugin_name"), s.get("row_id"), s.get("segment_slice")) for s in existing_sources}
                    for s in node.sources:
                        sd = s.to_dict()
                        key = (sd.get("plugin_name"), sd.get("row_id"), sd.get("segment_slice"))
                        if key not in seen:
                            existing_sources.append(sd)
                            seen.add(key)
                    con.execute(
                        "UPDATE nodes SET label = ?, properties = ?, sources = ?, updated_at = ? WHERE id = ?",
                        (node.label, json.dumps(merged_props), json.dumps(existing_sources), now, node.id),
                    )
                    written += 1
        return written

    def _import_edges(
        self,
        edges: List[GraphEdge],  # Edges to import
        merge_strategy: str  # "overwrite" | "skip" | "merge"
    ) -> int:  # Count of rows written (inserted or updated)
        """Import edges honoring merge_strategy (see import_graph)."""
        now = time.time()
        written = 0
        with self._connect() as con:
            for edge in edges:
                props_json = json.dumps(edge.properties)
                row = con.execute("SELECT properties FROM edges WHERE id = ?", (edge.id,)).fetchone()
                if row is None:
                    try:
                        con.execute(
                            "INSERT INTO edges (id, source_id, target_id, relation_type, properties, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?)",
                            (edge.id, edge.source_id, edge.target_id, edge.relation_type, props_json, now, now),
                        )
                        written += 1
                    except sqlite3.IntegrityError as err:
                        self.logger.warning(f"Edge import error (likely missing node): {err}")
                elif merge_strategy == "skip":
                    continue
                elif merge_strategy == "overwrite":
                    con.execute(
                        "UPDATE edges SET source_id = ?, target_id = ?, relation_type = ?, properties = ?, updated_at = ? WHERE id = ?",
                        (edge.source_id, edge.target_id, edge.relation_type, props_json, now, edge.id),
                    )
                    written += 1
                else:  # merge
                    merged = json.loads(row[0]) if row[0] else {}
                    merged.update(edge.properties)
                    con.execute(
                        "UPDATE edges SET properties = ?, updated_at = ? WHERE id = ?",
                        (json.dumps(merged), now, edge.id),
                    )
                    written += 1
        return written

    def export_graph(
        self,
        filter_query: Optional[GraphQuery] = None  # Optional filter
    ) -> GraphContext:  # Exported subgraph or full graph
        """Export the entire graph or a filtered subset."""
        # For now, dump everything (future: use filter_query)
        all_nodes = []
        all_edges = []

        with self._connect() as con:
            cur = con.execute("SELECT id, label, properties, sources, created_at, updated_at FROM nodes")
            for row in cur:
                all_nodes.append(self._row_to_node(row))

            cur = con.execute("SELECT id, source_id, target_id, relation_type, properties, created_at, updated_at FROM edges")
            for row in cur:
                all_edges.append(self._row_to_edge(row))

        return GraphContext(nodes=all_nodes, edges=all_edges)

    def query(
        self,
        sql: str,  # A single read-only SELECT (or WITH ... SELECT) statement
        params: Optional[List[Any]] = None  # Bound parameters for the statement
    ) -> Dict[str, Any]:  # {"columns": [...], "rows": [[...]], "row_count": int}
        """Execute a single read-only SELECT and return its rows (SG-41).

        Guards reject empty input, multiple statements, and anything not starting
        with SELECT/WITH. The statement runs on a fresh read-only connection
        (URI `mode=ro`), so even a query that slips past the prefix guard cannot
        mutate the database. Bound `params` use SQLite's qmark placeholders.
        """
        text = (sql or "").strip()
        while text.endswith(";"):
            text = text[:-1].strip()
        if not text:
            raise PluginInputError("query requires a non-empty SQL string", fields_invalid=["sql"])
        if ";" in text:
            raise PluginInputError("query accepts a single statement only", fields_invalid=["sql"])
        head = text.lstrip("(").split(None, 1)[0].lower()
        if head not in ("select", "with"):
            raise PluginInputError(
                "query allows read-only SELECT statements only", fields_invalid=["sql"],
            )
        con = sqlite3.connect(f"file:{self._db_path}?mode=ro", uri=True)
        try:
            cur = con.execute(text, tuple(params) if params else ())
            columns = [d[0] for d in cur.description] if cur.description else []
            rows = [list(r) for r in cur.fetchall()]
        finally:
            con.close()
        return {"columns": columns, "rows": rows, "row_count": len(rows)}

    def cleanup(self) -> None:
        """Clean up resources."""
        # SQLite connections are managed via context managers, nothing to do here
        pass


SQLiteGraphPlugin.supported_actions = collect_plugin_actions(SQLiteGraphPlugin)

